### ISSUE TITLE
[ASSETS] Record new Announcer VO

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#11]
During the reorganisation of the github stuff, you accidentally reverted to the old announcer voicelines so now we get to hear 14 year old blubs again lol.

**Comment by MotoLegacy** [comment]
This was an intentional revert as people criticized what would've universally been the "new" announcer types. 

We do need to move from Blubs' old, whisper-y lines but this time around I will be more considerate of NZ:P's overall theme.

I will keep this issue up but rename it to reflect the need for new recorded VOs.

**Comment by DerpedCrusader** [comment]
Unironically, maybe we could just hire like, 3 fiver voice actors and go with the set we think is the best

**Comment by MotoLegacy** [comment]
> Unironically, maybe we could just hire like, 3 fiver voice actors and go with the set we think is the best

Hi Casey,
I think I'd rather just sit on my mic on a groggy morning and tune the results in Tenacity. 

I think the problem was the inconsistency of quality between the attempted new ones, which were done by a professional audio engineer, and everything else in our game being very grassroots.

Trivially less cringey replacements that I can replicate for new Power-Ups and such feel like the way to go.

Feel free to argue otherwise,
Ian

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/assets/commit/24bb92f694df7a4e6f045b184ff7a4f797ff9fd8
