### ISSUE TITLE
[SUGGESTION] A way to utilize the secondary grenade on PSP

### ISSUE THREAD

**Issue by TheSubPlayer** [nzp-team/nzportable#134]
Well, it's currently not possible to use Bouncing Betty on PSP, and that's due to the lack of buttons.

![Sem Título-1](https://user-images.githubusercontent.com/110436924/213843675-931d8f58-cc29-4825-88df-2f52f51d7802.png)

On the PC, just press the key <kbd>4</kbd>  on the keyboard and the mine will be planted.

My suggestion is to use the combination of <kbd>SELECT</kbd>+<kbd>UPARROW</kbd> buttons to plant it.

**Comment by MotoLegacy** [comment]
Hi, this was actually an oversight - functionality for switching between grenades has been in game but was absent in the config file. This has been fixed in https://github.com/nzp-team/assets/commit/2c42daac4ac0ef50c16e7560964ef03fe471be98. You'll be able to switch grenades by double tapping SELECT when the nightly goes live.
