### ISSUE TITLE
[PSP] Hyper Agressive Culling on the PSP

### ISSUE THREAD

**Issue by Paindeluxe** [nzp-team/nzportable#169]
**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to the map called Corner.
2. Walk to the Table with the Radio.
3. Look at it from the corner of your camera
4. See that parts of the table including the complete Radio is missing

**Expected behavior**
_A clear and concise description of what you expected to happen._

The Table with the Radio only gets culled when out of the FOV of the player.

**Screenshots/Footage**
_If applicable, add screenshots or video to help explain your problem._

[The highest quality psp screencapture you ever saw](https://user-images.githubusercontent.com/104042185/216464166-b09c2528-ddc2-43fa-8668-280290413069.mov)

**Affected Platforms:**
- PSP 1000
- PSP GO
- PSP E-1000
- PSP 2000
- PSP 3000
# Please make note of any platforms you DID NOT test on.

- PSP 1000
- PSP GO
- PSP 2000
- PSP 3000
- PS VITA
- Nintendo Switch
- N3DS
- 3DS
- 2DS
- N3DSXL
- 3DSXL
- 2DSXL
- FTEQW (Windows, Mac, Linux, etc)

**Additional context**
_Add any other context about the problem here._

I found this with the default FOV of 63 also...

I do appreciate the extra FPS and Battery life.

**Comment by MotoLegacy** [comment]
Hey there -- technically not a bug. Engines cull things depending on their bounding box size, they don't check the actual dimensions of the meshes because that is computationally expensive. All `place_model` entities have the same (sorta-small) default bbox size, which is what causes that. The soon-coming `misc_model` changes will mitigate this problem by letting mappers input custom sizes for their props much easier.
