### ISSUE TITLE
Control mouselook via touchscreen + controls discussion

### ISSUE THREAD

**Issue by TheVGMLover** [nzp-team/nzportable#337]
I noticed with the latest update, the circle pad no longer controls the camera and only allows movement. It does not activate sprint and stance the same way the face buttons do. In fact, using the circle pad and pressing the face buttons in the same direction will double your character's movement speed. 
This does not seem intentional, and the fact that I'm now stuck with using the C-Nub for camera control is not ideal for me (I can still set the face buttons to look around, but they'll still activate the sprint and stance functions, so that's out of the question).

The other control issue I want to highlight is the diving controls. It activates when using any of the knife controls. This seems like an oversight and has not been addressed since long before the uncapped framerate update. 
One potential fix for this is to allow the jump control to be held for a split-second to activate it, or to give the diving function its own dedicated space on the touch screen.

Speaking of the touch screen... can we allow that to control the camera, too? The 3DS version of Quake itself has that as an option.

**Comment by MotoLegacy** [comment]
Hi there. Melee while sprinting to dive is not an oversight and has been a feature since beta in 2011.

Sorry to hear you're generally displeased with the control changes I made, this was dominantly to streamline the use of the C-Stick for camera controls instead of having to toggle it on in the menus. It seems like part of the issue however is not knowing the new control bindings, so I will list them here:

- ZL is used to toggle sprinting while moving
- ZR throws equipment (grenade/betty)
- T1 switches active equipment from Grenades to Bouncing Betties
- T2 is assigned to jumping
- T3 is assigned to reload
- T4 switches weapons
- T5 melees

On top of this the default face button and dpad configuration is default for compatibility with old model units but are configurable via `config.cfg` and will be assignable via the menu eventually.

@DerpedCrusader stated they were going to revise the bottom screen graphic to reflect the touch screen bindings. Otherwise I am sorry this was not communicated very well.

Thanks for the suggestion about making the empty space on the touchscreen for mouse look, I will look into this when I can.

**Comment by TheVGMLover** [comment]
Can the Circle Pad be given the option to be toggled between camera and movement control as well?

**Comment by MotoLegacy** [comment]
addressed in https://github.com/nzp-team/glquake/commit/1c38cda5aab99216addecdefc6d96526993b432a
