### ISSUE TITLE
[SERVER] downloads don't work

### ISSUE THREAD

**Issue by Revnova** [nzp-team/nzportable#34]
When you join someone who has files that you don't, nothing actually downloads. Progress Bar means nothing. so you're just stuck waiting. unless you use the "finishdl" command

The expected outcome is that it should work.

![image](https://user-images.githubusercontent.com/34180180/171496859-47971660-2d47-47f2-bad3-78c8e2cfb87b.png)

currently only tested on PC

**Comment by MotoLegacy** [comment]
Fixed in https://github.com/nzp-team/quakec/commit/92f38d906aed00866b5743f9d550bf5556cd6962
![fte-20220602085519-0](https://user-images.githubusercontent.com/26030250/171634591-09de574b-3266-4509-8ecf-5e80a34f63d1.png)
![fte-20220602085534-0](https://user-images.githubusercontent.com/26030250/171634594-a2c55d63-e952-41d7-8b62-6e52bf29a353.png)
