### ISSUE TITLE
Potential Weapon Stat Inaccuracy

### ISSUE THREAD

**Issue by oStarist** [nzp-team/nzportable#358]
**Describe your suggestion**
I have noticed that explosives don't really do that much damage to zombies, like grenades for example don't kill on round 1, it just makes them crawlers
I have also noticed that most wall weapons and bullet weapons (anything not a wonder weapon) really need a small damage and firerate buff
Me and other players have agreed that something like the bo1 health calculation would be nice if it's not already like that, if not then at least buff the weapons or something, it's pretty hard to get through the early rounds when trying to set the maps up

**Expected behavior**
For the health to be tweaked somewhat, or weapons to be buffed in firerate and damage to some degree

**Context**
bo1 zombie health calculation script:
```gsc
	set_zombie_var( "zombie_health_increase", 			100,	false,	column );	//	cumulatively add this to the zombies' starting health each round (up to round 10)
	set_zombie_var( "zombie_health_increase_multiplier",0.1, 	true,	column );	//	after round 10 multiply the zombies' starting health by this amount
	set_zombie_var( "zombie_health_start", 				150,	false,	column );	//	starting health of a zombie at round 1

	level.zombie_health = level.zombie_vars["zombie_health_start"]; 
	for ( i=2; i<=round_number; i++ )
	{
		// After round 10, get exponentially harder
		if( i >= 10 )
		{
			level.zombie_health += Int( level.zombie_health * level.zombie_vars["zombie_health_increase_multiplier"] ); 
		}
		else
		{
			level.zombie_health = Int( level.zombie_health + level.zombie_vars["zombie_health_increase"] ); 
		}
	}
```

**Comment by MotoLegacy** [comment]
Health calculation looks to produce the same output to me, I used Black Ops to test, I don't like WaWs (but obviously not identical since we don't use CoD scripts for reference, license reasons):
https://github.com/nzp-team/quakec/blob/aec68db169a909ed1930be5f670eaae0b1252926/source/server/ai/zombie_core.qc#L1435

The logic for crawler creation is bugged, so explosive weapon damage can be accurate and the crawler just executes falsely instead of killing them.

Weapon Damage stats originate from the Wiki, they feel correct to me. Fire rate is *definitely* correct or near-correct, I tested that one first hand. Please give a video demonstration showing me how the damage is not correct from the real deal.

**Comment by oStarist** [comment]
well, if they are from the wiki then they should be fine, we’ve just noticed they fall off pretty quickly which was unusual to us

and i apologize for that, will refrain from doing so in the future

**Comment by MotoLegacy** [comment]
Closing as requested follow-up was not received. Feel free to re-open the issue if it persists.
