### ISSUE TITLE
[SUGGESTION] [3DS] Are you SURE that mapping the dive button to the knife button is a good idea?

### ISSUE THREAD

**Issue by TheVGMLover** [nzp-team/nzportable#413]
**Describe your suggestion**
Put the dive button somewhere else, please! Maybe D-Pad up, since the grenade button is now on the ZR button!

**Expected behavior**
I DON'T accidentally dive and get stepped on in the first round.

**Additional context**
For those unfamiliar, the knife and dive button is on the D-Pad down button. D-Pad left reloads, D-Pad right switches weapons, and there's two grenade buttons now: one on D-Pad up and one on the ZR button. To dive, you have to use the sprint button (ZL) and then use the dive button. To knife, you cannot sprint. If you're sprinting and need to knife, you have to wait for the sprinting animation to stop, which really feels longer than it should.

**Comment by MotoLegacy** [comment]
I've left this issue sit open for a while because I wasn't sure how to respond based on your tone in the title.

Regardless, it's important (once again) to note that NZ:Ps control scheme must accommodate both "Old" and "New" 3DS models. It's the standard PSP control layout at heart, with some re/double binds for "New" 3DS' extra buttons. Hence your both Up and ZR binds for throwing equipment. This feels neglected by you, which is unfortunate. 

I understand you feel frustrated about meleeing after a sprinting sequence and diving as a result, but "animation is too long" sounds like you've instead identified a bug which ultimately should be properly reported.

What I am going to do is change the default bind for Down to change stance instead, since melee is a touch screen option. In the mean time, if you believe you've identified a sprinting bug (I don't doubt it's existence on 3DS), feel free to report that. For now though I am going to consider this matter closed. Thanks!
