### ISSUE TITLE
Zombies getting stuck in barriers

### ISSUE THREAD

**Issue by Ascension240** [nzp-team/nzportable#417]
**Describe the bug**
On certain maps, the zombies will get stuck in the barriers

**To Reproduce**
1. Go on Corner
2. Get to like round 25 or something
3. Let them spawn in, they'll get stuck

**Expected behavior**
The zombies to come out of the barrier

**Screenshots/Footage**

https://github.com/nzp-team/nzportable/assets/140561038/7799c630-7d92-4198-9d7e-ee2b1bda0b99

**Affected Platforms**
- FTEQW (Windows, Mac, Linux, WebGL etc), only platform tested on.

**Additional context**
This could be related to https://github.com/nzp-team/nzportable/issues/408

**Comment by TBOINDSI** [comment]
that happens somewhat often, happens on psp 64 also

**Comment by MotoLegacy** [comment]
I'm not able to reproduce this given the provided tests, even if I abuse carpenter to make them horde up at the spot. Video attached -- let me know if this still occurs for you at all. It may have (accidentally) been fixed with https://github.com/nzp-team/quakec/commit/9866a529b07f48d0662b774d643591c181aa6937
