### ISSUE TITLE
[SERVER] PaPing with a dual wield weapon causes infinite switch delay

### ISSUE THREAD

**Issue by ethancoola** [nzp-team/nzportable#45]
Not exactly sure what ended up causing it, but was playing on boxxer and was on round 25 with all the perks (except mule kick). I had M&S and went to PaP the Thompson, and when I picked it up I could no longer interact or throw grenades.

**Comment by BCDeshiG** [comment]
This bug is not specific to the Mustang and Sally i've noticed. When you pack-a-punch any weapon and you collect it before the cookie animation finishes, you can no longer sprint or interact with perk machines/wallbuys. Upgrading a different weapon and waiting for the cookie animation to finish fixes it (you can still buy from mystery box if need be).

**Comment by BCDeshiG** [comment]
Video demonstration:

https://user-images.githubusercontent.com/29164668/182972929-e4a8bf22-8458-42cf-8811-e3dbb0f38f91.mp4

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/aa9965e2f177f97f7379b49c119fbfe38ffd81c3
