### ISSUE TITLE
Zapper doesn't damage you when jumping through it

### ISSUE THREAD

**Issue by BCDeshiG** [nzp-team/nzportable#61]
When the zapper is active, you can jump through it without taking any damage.
Walking through it does damage you however.

Only tested on PC.

https://user-images.githubusercontent.com/29164668/201474735-681e14e8-7200-48be-8f55-fe7f5c0f232d.mp4

**Comment by MotoLegacy** [comment]
fixed in https://github.com/nzp-team/quakec/commit/3e258fea2fd93ed28c4101d2b791aad57018af50

also has the side effect of fixing maps like Bunker-Defense.

![fte-20230113105402-0](https://user-images.githubusercontent.com/26030250/212362905-0e6e6ebb-c16c-4bc2-be02-86ced987a5e7.png)
![fte-20230113105415-0](https://user-images.githubusercontent.com/26030250/212362912-ab050b29-db9a-4c10-923d-3e81bd01ce92.png)
