### ISSUE TITLE
Close-range Melee Detection Failure

### ISSUE THREAD

**Issue by Laser327** [nzp-team/nzportable#701]
**Describe the bug**
Knifing a zombie on point-blank range doesnt work sometimes and u will get a sound of knifing a wall instead (EVEN WHEN STANDING IN FRONT OF THE ZOMBIE)

**To Reproduce**
Just try to knife a zombie on point-blank range or/and closer.

**Expected behavior**
Well. Its self explanatory.

**Screenshots/Footage**
Not gonna provide any footage since i cant be bothered to re-install OBS again, but then again the problem 
is self explanatory

**Affected Platforms**
- PS Vita (110X) since its the only platform i play it on

**Comment by Laser327** [comment]
Idk if Cypress decreased the range of knifing but if thats the case she lowered the range a bit TOO MUCH, cuz now u cant even knife a zombie properly even when you're standing at a range where the zombie can hit you.

**Comment by MotoLegacy** [comment]
> Not gonna provide any footage since i cant be bothered to re-install OBS again, but then again the problem
is self explanatory

Sure. Don't spend the time making sure a bug report is quality, just say it is self explanatory and say you don't want to do the work!

I'm only keeping this open because I know this has been a long standing bug. This doesn't fly here otherwise. If you're too lazy to file a report, just don't file a report and let your bug rot. Have some perception of due diligence, thanks!

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/commit/090e4832920963d466cdf69c842b0772e4cf5f73
